DROP TABLE IF EXISTS `scheduler_job_info`;
DROP TABLE IF EXISTS `scheduler_job_info_history`;
DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
DROP TABLE IF EXISTS QRTZ_CALENDARS;

CREATE TABLE scheduler_job_info (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  cron_expression varchar(255) DEFAULT NULL,
  cron_job varchar(255) DEFAULT 'Y',
  group_id int not null default 0,
  cat_id int not null default 0,
  job_class varchar(255) DEFAULT NULL,
  job_group varchar(255) DEFAULT NULL,
  job_name varchar(255) DEFAULT NULL,
  repeat_time bigint(20) DEFAULT NULL,
  params varchar(255) DEFAULT NULL,
  param0 varchar(255) DEFAULT NULL,
  param1 varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  action_type int not null default 0,
  automatic int not null default 0,
  scheduleTime varchar(200) DEFAULT NULL,
  nextFireTime varchar(200) DEFAULT NULL,
  lastFireTime varchar(200) DEFAULT NULL,
  state varchar(200) DEFAULT NULL,
  status_job int not null default 0,
  notification_id int not null default 0,
  PRIMARY KEY (id)
) ENGINE=INNODB;


create table scheduler_job_info_groups(
	group_id int not null auto_increment,
	group_name varchar(200) not null default '',
	group_descriptions varchar(255) not null default '',
	primary key(group_id)
)ENGINE=INNODB;

CREATE TABLE scheduler_job_info_category(
	cat_id int not null auto_increment,
	job_class varchar(255) DEFAULT NULL,
	job_label varchar(255) DEFAULT NULL,
	primary key(cat_id)
)ENGINE=INNODB;



CREATE TABLE scheduler_job_info_history (
  info_id int(10) not null auto_increment,
  id bigint(20) NOT NULL,
  cron_expression varchar(255) DEFAULT NULL,
  cron_job varchar(255) DEFAULT 'Y',
  job_class varchar(255) DEFAULT NULL,
  job_group varchar(255) DEFAULT NULL,
  job_name varchar(255) DEFAULT NULL,
  repeat_time bigint(20) DEFAULT NULL,
  params varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  action_type int not null default 0,
  automatic int not null default 0,
  created_date date,
  job_result text not null,
  primary key(info_id)
) ENGINE=INNODB;

create table scheduler_notification_type(
	type_id int not null auto_increment,
	notification_type varchar(200) not null,
	description varchar(300) not null,
	flag_active int not null default 1,
	primary key(type_id)
)ENGINE=INNODB;


create table scheduler_notification(
	notification_id int not null auto_increment,
	notification_type_id int not null,
	params varchar(200) default null,
	fromemail varchar(200) default null,
	toemail varchar(200) default null,
	ccemail varchar(200) default null,
	bccemail varchar(200) default null,
	subject_email varchar(200),
	message varchar(300),
	description varchar(300),
	flag_active int not null default 1,
	primary key(notification_id)
)ENGINE=INNODB;

create table scheduler_notification_history(
	history_id int not null auto_increment,
	notification_id int,
	info_id  int,
	error int,
	message varchar(300) not null default '',
	create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	primary key(history_id)
)ENGINE=INNODB;

CREATE TABLE QRTZ_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE BOOLEAN NOT NULL,
IS_NONCONCURRENT BOOLEAN NOT NULL,
IS_UPDATE_DATA BOOLEAN NOT NULL,
REQUESTS_RECOVERY BOOLEAN NOT NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(250) NULL,
NEXT_FIRE_TIME BIGINT(19) NULL,
PREV_FIRE_TIME BIGINT(19) NULL,
PRIORITY INTEGER NULL,
TRIGGER_STATE VARCHAR(16) NOT NULL,
TRIGGER_TYPE VARCHAR(8) NOT NULL,
START_TIME BIGINT(19) NOT NULL,
END_TIME BIGINT(19) NULL,
CALENDAR_NAME VARCHAR(200) NULL,
MISFIRE_INSTR SMALLINT(2) NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
REPEAT_COUNT BIGINT(7) NOT NULL,
REPEAT_INTERVAL BIGINT(12) NOT NULL,
TIMES_TRIGGERED BIGINT(10) NOT NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_CRON_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
CRON_EXPRESSION VARCHAR(120) NOT NULL,
TIME_ZONE_ID VARCHAR(80),
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 BOOLEAN NULL,
    BOOL_PROP_2 BOOLEAN NULL,
    TIME_ZONE_ID VARCHAR(80) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
    REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_BLOB_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
BLOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP),
FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_CALENDARS (
SCHED_NAME VARCHAR(120) NOT NULL,
CALENDAR_NAME VARCHAR(200) NOT NULL,
CALENDAR BLOB NOT NULL,
PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))
ENGINE=InnoDB;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;

CREATE TABLE QRTZ_FIRED_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
ENTRY_ID VARCHAR(140) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,
INSTANCE_NAME VARCHAR(200) NOT NULL,
FIRED_TIME BIGINT(19) NOT NULL,
SCHED_TIME BIGINT(19) NOT NULL,
PRIORITY INTEGER NOT NULL,
STATE VARCHAR(16) NOT NULL,
JOB_NAME VARCHAR(200) NULL,
JOB_GROUP VARCHAR(200) NULL,
IS_NONCONCURRENT BOOLEAN NULL,
REQUESTS_RECOVERY BOOLEAN NULL,
PRIMARY KEY (SCHED_NAME,ENTRY_ID))
ENGINE=InnoDB;

CREATE TABLE QRTZ_SCHEDULER_STATE (
SCHED_NAME VARCHAR(120) NOT NULL,
INSTANCE_NAME VARCHAR(200) NOT NULL,
LAST_CHECKIN_TIME BIGINT(19) NOT NULL,
CHECKIN_INTERVAL BIGINT(19) NOT NULL,
PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))
ENGINE=InnoDB;

CREATE TABLE QRTZ_LOCKS (
SCHED_NAME VARCHAR(120) NOT NULL,
LOCK_NAME VARCHAR(40) NOT NULL,
PRIMARY KEY (SCHED_NAME,LOCK_NAME))
ENGINE=InnoDB;

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME,JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME,CALENDAR_NAME);
CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);


insert into scheduler_job_info_groups(group_name,group_descriptions) values('E-Lions','E-lions');
insert into scheduler_job_info_groups(group_name,group_descriptions) values('Ofac-Engine','Ofac Engine');





insert into scheduler_job_info_category(cat_id,job_class,job_label)
values('1','com.app.quartz.engine.jobs.GalleryJob','GALLERY JOB');
insert into scheduler_job_info_category(cat_id,job_class,job_label)
values('2','com.app.quartz.engine.jobs.SimpleJob','SIMPLE JOB');
insert into scheduler_job_info_category(cat_id,job_class,job_label)
values('3','com.app.quartz.engine.jobs.HttpJob','HTTP');


insert into scheduler_notification_type(
	notification_type,
	description,
	flag_active
) values('gmail','Gmail description',1);



insert into scheduler_notification(notification_type_id,fromemail,toemail,subject_email,description,flag_active)
values(1,'patartimotiustambunan@gmail.com','patartimotiustambunan@gmail','test','test',1);

INSERT INTO `scheduler_job_info` (`cron_expression`,`cat_id`,`group_id`, `job_group`, `job_name`, `cron_job`, `repeat_time`,`action_type`,`automatic`,`notification_id`) 
VALUES ( '16/05/2020 21:24:00',2,1, 'Test_Cron2', 'Sample Cron2', 'N', NULL,1,1,1);


INSERT INTO `scheduler_job_info` (`cron_expression`,`cat_id`,`group_id`, `job_group`, `job_name`, `cron_job`, `repeat_time`,`action_type`,`automatic`,`notification_id`,`url`) 
VALUES ( '0/5 * * * * ?',3,1, 'Test_Cron23', 'httpbypatar', 'Y', NULL,1,1,1,'https://gorest.co.in/public-api/users?_format=json&access-token=dggoqBMlXjB_GOGOurCY3UbO8pp5_cam1bdn');

INSERT INTO `scheduler_job_info` (`cron_expression`,`cat_id`,`group_id`, `job_group`, `job_name`, `cron_job`, `repeat_time`,`action_type`,`automatic`,`notification_id`,`url`) 
VALUES ( '31/05/2020 18:55:00',3,1, 'Test_Cron233', 'gallery001', 'N', NULL,1,1,1,'https://jsonplaceholder.typicode.com/todos/1');


commit;